spring:
  datasource:
    url: jdbc:mysql://datavotacao.cp48s4m8m6x8.sa-east-1.rds.amazonaws.com:3306/votacaoBanco?createDatabaseIfNotExist=true
    username: admin
    password: 0c0ZsGcFsoRnIXGx3Z0v
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: false
